### ISSUE TITLE
h1 should be followed by h2s

### ISSUE THREAD

**Issue by emmalearnscode** [goobric/linkfreeInformation#2]
There's a strict hierarchy with heading tags that should be followed so that an h1 is always followed by h2s and if the h2 needs breaking down further it's done with h3 just like how headings and subheadings work in a book. For accessibility reasons it's not good to jump over heading sizes, if you want a smaller size then you should use styling to modify them instead of choosing them based on their size.

**Comment by goobric** [comment]
TY sm for your input and advice Emma, yes for accessibility this is very important.
I have updated the markup
